const MAIN_SCENE = 'main';
const BROADCAST_SCENE = 'broadcastScene';
const ALL_CHATS_SCENE = 'allChats';
const CHAT_DETAILED_SCENE = 'chatDetailed';
const CREATE_CHAT_SCENE = 'createChat';
const CHAT_LIBRARY_SOURCE_SCENE = 'chatLibrarySource';
const LIBRARY_SCENE = 'libraryScene';
const LIBRARY_SOURCE_SCENE = 'librarySource';
const ADD_LIBRARY_SOURCE_SCENE = 'addLibrarySource';
const ADD_YOUTUBE_SCENE = 'addYoutube';
const ADD_RADIO_SCENE = 'addRadio';
const CHAT_LIBRARY_SCENE = 'chatLibrary';
const ADD_CHAT_LIBRARY_SOURCE_SCENE = 'addChatLibrarySource';
const INFORMATION_SCENE = 'information';
const USER_PROFILE_SCENE = 'userProfile';
const SUBSCRIPTION_SCENE = 'subscription';
const ADMIN_PANEL_SCENE = 'adminPanel';
const ADD_ADMIN_SCENE = 'addAdmin';
const ADD_MODER_SCENE = 'addModer';
const ADMIN_TOPUP_USER_BALANCE_SCENE = 'adminTopupUserBalance';
const ADMIN_SET_USER_SUBSCRIPTION = 'adminSetUserSubscription';
const ADMIN_MANAGE_USERS_SCENE = 'adminManageUsers';
const ADMIN_SET_REF_BONUS_SCENE = 'setRefBonus';
const ADD_SOURCE_TO_CHAT_SCENE = 'addSourceToChat';
const BALANCE_SCENE = 'balance';
const ADD_TWITCH_SCENE = 'addTwitch';
const ADD_MOVIE_SCENE = 'addMovie';
const CHOOSE_LANGUAGE = 'chooseLanguage';

module.exports = {
	ALL_CHATS_SCENE,
	CHAT_DETAILED_SCENE,
	CREATE_CHAT_SCENE,
	MAIN_SCENE,
	BROADCAST_SCENE,
	LIBRARY_SCENE,
	LIBRARY_SOURCE_SCENE,
	ADD_LIBRARY_SOURCE_SCENE,
	ADD_YOUTUBE_SCENE,
	ADD_RADIO_SCENE,
	CHAT_LIBRARY_SCENE,
	ADD_CHAT_LIBRARY_SOURCE_SCENE,
	INFORMATION_SCENE,
	USER_PROFILE_SCENE,
	SUBSCRIPTION_SCENE,
	ADMIN_PANEL_SCENE,
	ADD_ADMIN_SCENE,
	ADMIN_TOPUP_USER_BALANCE_SCENE,
	ADMIN_SET_USER_SUBSCRIPTION,
	ADD_MODER_SCENE,
	ADMIN_MANAGE_USERS_SCENE,
	ADD_SOURCE_TO_CHAT_SCENE,
	BALANCE_SCENE,
	ADD_TWITCH_SCENE,
	ADMIN_SET_REF_BONUS_SCENE,
	ADD_MOVIE_SCENE,
	CHAT_LIBRARY_SOURCE_SCENE,
	CHOOSE_LANGUAGE
};