const MAIN_SCENE = 'main';
const BROADCAST_SCENE = 'broadcastScene';
const ALL_CHATS_SCENE = 'allChats';
const CHAT_DETAILED_SCENE = 'chatDetailed';
const CREATE_CHAT_SCENE = 'createChat';
const LIBRARY_SCENE = 'libraryScene';
const LIBRARY_SOURCE_SCENE = 'librarySource';
const ADD_SOURCE_SCENE = 'addSource';
const ADD_YOUTUBE_SCENE = 'addYoutube';
const ADD_RADIO_SCENE = 'addRadio';
const CHAT_LIBRARY_SCENE = 'chatLibrary';
const ADD_CHAT_LIBRARY_SOURCE_SCENE = 'addChatLibrarySource';
const INFORMATION_SCENE = 'information';
const USER_PROFILE_SCENE = 'userProfile';
const SUBSCRIPTION_SCENE = 'subscription';

module.exports = {
	ALL_CHATS_SCENE,
	CHAT_DETAILED_SCENE,
	CREATE_CHAT_SCENE,
	MAIN_SCENE,
	BROADCAST_SCENE,
	LIBRARY_SCENE,
	LIBRARY_SOURCE_SCENE,
	ADD_SOURCE_SCENE,
	ADD_YOUTUBE_SCENE,
	ADD_RADIO_SCENE,
	CHAT_LIBRARY_SCENE,
	ADD_CHAT_LIBRARY_SOURCE_SCENE,
	INFORMATION_SCENE,
	USER_PROFILE_SCENE,
	SUBSCRIPTION_SCENE
};